apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
      - name: video
        image: video-service:1.0
        ports:
        - containerPort: 5000
        env:
        - name: AUDIO_SERVICE
          value: "http://audio-service:5001/extract"
        volumeMounts:
        - name: shared-storage
          mountPath: /data/videos
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    app: video
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

